steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}',
          '--build-arg', 'image_name=${_IMAGE_NAME}',
          '--cache-from', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest',
          '-f', 'pip_package/presubmit.Dockerfile', '.'
        ]
  timeout: 14400s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']

substitutions:
    _PYTHON_VERSION: '3.8'
    _RELEASE_VERSION: 'nightly'  # or rX.Y
    _IMAGE_NAME: 'paxml_presubmit_${_RELEASE_VERSION}_${_PYTHON_VERSION}'
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
timeout: 24000s
