steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--build-arg', 'python_version=${_PYTHON_VERSION}',
          '--build-arg', 'release_version=${_RELEASE_VERSION}',
          '-t', 'gcr.io/${PROJECT_ID}/paxml:${_IMAGE_NAME}',
          '-f', 'paxml/pip_package/Dockerfile', '.'
        ]
  timeout: 14400s
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: ['-c', 'docker tag gcr.io/${PROJECT_ID}/paxml:${_IMAGE_NAME} gcr.io/${PROJECT_ID}/paxml:${_IMAGE_NAME}_$(date -u +%Y%m%d)']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'gcr.io/${PROJECT_ID}/paxml']
  timeout: 1800s
- name: 'gcr.io/${PROJECT_ID}/paxml:${_IMAGE_NAME}_$(date -u +%Y%m%d)'
  entrypoint: 'bash'
  args: ['-c', 'source ./collect_wheels.sh && collect_wheels ${_RELEASE_VERSION}']

substitutions:
    _PYTHON_VERSION: '3.8'
    _RELEASE_VERSION: 'nightly'  # or rX.Y
    _IMAGE_NAME: '${_RELEASE_VERSION}_${_PYTHON_VERSION}'
#    _UPLOAD_SUBDIR: "20220819"
options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
timeout: 24000s
artifacts:
  objects:
    location: 'gs://pax-on-cloud-tpu-project/wheels/$(date -u +%Y%m%d)'
#    location: 'gs://pax-on-cloud-tpu-project/wheels/${_UPLOAD_SUBDIR}'
    paths: ['/**/*.whl']
